using MiVic.Core.Numerics;
using MiVic.Core.Pathfinding;
using MiVic.Core.Sim;
using MiVic.Core.Terrain;
using MiVic.Game.Data;
using MiVic.Game.Rendering.Gltf;
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;

namespace MiVic.Game.Rendering;

/// <summary>
/// Draws the deck of every crossing on the map, one block per cell, from models generated by
/// <c>tools/blender/build_bridge.py</c>.
/// <para>
/// <b>A crossing is one block repeated.</b> The whole of a bridge — one cell or twenty-four —
/// is the same mesh placed once per cell of the span, turned to the way the span runs. That is
/// what makes the art affordable and the damage legible: a hole is a block that is not drawn,
/// so the player sees exactly which section the artillery took out, and a fifteen-cell crossing
/// costs one more instance rather than one more model.
/// </para>
/// <para>
/// <b>Rails are placed per side, from the map.</b> A block carries none; the rail is its own
/// mesh, and one is drawn along a side of a block when nothing can be driven off there —
/// which is asked of the terrain layer, not guessed from the bridge. So the long sides of a
/// span get rails because the water beside them is impassable, the ends do not because they
/// meet the bank, the shared block of a crossroads has none because deck continues all four
/// ways, and the dead side of a T gets one. Baking rails into the block could not express any
/// of that: it could only ever put them along the block's own axis, which is a rail across the
/// way through at a junction and a bare edge over open water at the end of a broken span.
/// </para>
/// <para>
/// The block is laid on the <em>water line</em>, not on the ground: the piers in the model stop
/// at its own base and what they continue into is the lake, which is opaque and drawn first. A
/// crossing is therefore placed by the surface the player sees rather than by the bed metres
/// under it, which is the same rule the click projection follows.
/// </para>
/// <para>
/// The rails are painted in the owner's colour, which is what the kit's paint mask is for: the
/// per-instance tint is the faction's colour, the deck's boards carry a mask of zero and keep
/// their timber, and the rail along each side says whose crossing this is without a flag.
/// </para>
/// </summary>
public sealed class BridgeRenderer : IDisposable
{
    /// <summary>The generated pieces: the deck block, and one panel of its rail.</summary>
    private static readonly string BlockFile = "bridge_block.glb";
    private static readonly string RailFile = "bridge_rail.glb";

    private static readonly string ModelFolder = Path.Combine("Content", "Models", "Generated");

    /// <summary>
    /// A quarter turn for each side of a block, in the order (−Z, +Z, −X, +X). The rail is
    /// modelled on one edge of the block's own frame, so the side it lands on is that turn and
    /// nothing else — no per-side geometry, and no constant from the art duplicated here.
    /// </summary>
    private static readonly Matrix[] SideTurns =
    [
        Matrix.Identity,
        Matrix.CreateRotationY(MathHelper.Pi),
        Matrix.CreateRotationY(MathHelper.PiOver2),
        Matrix.CreateRotationY(-MathHelper.PiOver2),
    ];

    private static readonly (int DX, int DZ)[] Sides = [(0, -1), (0, 1), (-1, 0), (1, 0)];

    private readonly InstancedRenderer _renderer;
    private readonly List<string> _missing = [];

    private InstancedRenderer.Mesh? _block;
    private InstancedRenderer.Mesh? _rail;

    // Two arrays rather than one, because an instanced draw call takes a contiguous run and the
    // deck and its rails are different meshes.
    private InstanceData[] _blocks = [];
    private InstanceData[] _rails = [];
    private int _blockCount;
    private int _railCount;

    public BridgeRenderer(InstancedRenderer renderer, string baseDirectory)
    {
        ArgumentNullException.ThrowIfNull(renderer);
        ArgumentException.ThrowIfNullOrWhiteSpace(baseDirectory);

        _renderer = renderer;

        // No rescaling and no orientation fixup: both pieces are modelled in metres at the size of
        // one navigation cell, long along their own X, and the placement turns them.
        //
        // The rail is imported without the usual centring, because it is modelled *inside the
        // block's frame* — standing on the deck's edge — and is placed by a turn about the block's
        // centre. Centring it on its own bounds moved it to the middle of the deck, which drew a
        // rail down the length of every bridge; the position of a piece authored in another
        // piece's frame is the art's decision, not something to normalise away.
        ModelImportOptions blockOptions = new(
            TargetSizeMetres: 0f,
            AlignLongestHorizontalAxis: false);

        ModelImportOptions railOptions = blockOptions with { CentreOnOwnBounds = false };

        _block = Load(baseDirectory, BlockFile, blockOptions);
        _rail = Load(baseDirectory, RailFile, railOptions);
    }

    /// <summary>How many models loaded: two when the art is complete, none when it is absent.</summary>
    public int ShapeCount => (_block is null ? 0 : 1) + (_rail is null ? 0 : 1);

    /// <summary>What was loaded and what was not, for the fixtures and the report.</summary>
    public string Summary => _block is not null && _rail is not null
        ? $"{BlockFile} and {RailFile} loaded"
        : _missing.Count == 0
            ? "no bridge blocks loaded"
            : $"bridge blocks missing: {string.Join(", ", _missing)}";

    private InstancedRenderer.Mesh? Load(string baseDirectory, string file, ModelImportOptions options)
    {
        string path = Path.Combine(baseDirectory, ModelFolder, file);

        if (!File.Exists(path))
        {
            _missing.Add(file);
            return null;
        }

        try
        {
            ModelData model = GltfLoader.LoadModel(path, options);
            return _renderer.CreateMesh(ModelBake.Flatten(model, out _));
        }
        catch (Exception exception) when (exception is IOException or InvalidDataException or NotSupportedException)
        {
            _missing.Add($"{file}: {exception.Message}");
            return null;
        }
    }

    /// <summary>
    /// Collects the deck and the rails. Returns how many instances were written.
    /// <para>
    /// Walked by cell rather than by crossing, because a block belongs to the cell: that is what
    /// makes a destroyed block a hole in the deck, and what lets the rails be decided by what is
    /// beside the cell rather than by which crossing laid it.
    /// </para>
    /// </summary>
    public int Collect(SimWorld world)
    {
        ArgumentNullException.ThrowIfNull(world);

        _blockCount = 0;
        _railCount = 0;

        if (_block is null)
        {
            return 0;
        }

        Bridgeworks bridgeworks = world.Bridgeworks;
        NavGrid navigation = world.Navigation;
        TerrainLayer terrain = world.TerrainTypes;
        float water = terrain.WaterLevelMm / (float)WorldPos.MmPerMetre;

        if (_blocks.Length < bridgeworks.CellCount)
        {
            _blocks = new InstanceData[bridgeworks.CellCount];
            _rails = new InstanceData[bridgeworks.CellCount * Sides.Length];
        }

        for (int index = 0; index < bridgeworks.CellCount; index++)
        {
            if (!bridgeworks.TryGetBlock(index, out BridgeBlock block))
            {
                continue;
            }

            // The block is long along its own X, which is the axis a span along X runs; a span
            // along Z is the same block turned a quarter turn. The turns are counted rather than
            // stored as a matrix because the *rail* needs the same rotation applied to a
            // direction, and two encodings of one turn are two things to keep in step.
            int quarters = block.Axis == BridgeAxis.AlongZ ? 1 : 0;
            Matrix turn = quarters == 0
                ? Matrix.Identity
                : Matrix.CreateRotationY(MathHelper.PiOver2);

            int cellX = navigation.CellX(index);
            int cellZ = navigation.CellZ(index);
            var centre = new Vector3(
                (navigation.OriginMm + (cellX * navigation.CellSizeMm) + (navigation.CellSizeMm / 2)) / (float)WorldPos.MmPerMetre,
                water,
                (navigation.OriginMm + (cellZ * navigation.CellSizeMm) + (navigation.CellSizeMm / 2)) / (float)WorldPos.MmPerMetre);

            Vector4 colour = OwnerColour(block.Team);

            _blocks[_blockCount++] = new InstanceData(turn * Matrix.CreateTranslation(centre), colour);

            if (_rail is null)
            {
                continue;
            }

            for (int side = 0; side < Sides.Length; side++)
            {
                (int dx, int dz) = Sides[side];

                // The rail's side is a side of the *block*, so the neighbour it must be judged
                // against is the one across that side once the block has been turned — the same
                // quarter turn the instance above takes. Judging it in world directions instead
                // put every rail of a north-south span on the wrong side of it, which is a rail
                // across the way through at a junction and a bare edge over open water: exactly
                // the fault the per-side rails were written to remove, one turn out.
                for (int quarter = 0; quarter < quarters; quarter++)
                {
                    (dx, dz) = (dz, -dx);
                }

                if (!NeedsRail(bridgeworks, terrain, navigation, cellX + dx, cellZ + dz))
                {
                    continue;
                }

                _rails[_railCount++] = new InstanceData(
                    turn * SideTurns[side] * Matrix.CreateTranslation(centre),
                    colour);
            }
        }

        return _blockCount + _railCount;
    }

    /// <summary>
    /// True when a rail belongs along the edge between a deck cell and the cell beside it: there
    /// is no deck to continue onto, and nothing can be driven off there either.
    /// <para>
    /// The question is put to the terrain layer rather than to the bridge, and that is the whole
    /// point: a ford the generator carved is passable ground with no deck on it, so a rail there
    /// would wall off a way the pathfinder is willing to take. The rail follows the simulation's
    /// own answer about whether a vehicle may leave the deck, which is the only answer that
    /// cannot disagree with what a unit actually does.
    /// </para>
    /// </summary>
    private static bool NeedsRail(
        Bridgeworks bridgeworks,
        TerrainLayer terrain,
        NavGrid navigation,
        int cellX,
        int cellZ)
    {
        int neighbour = navigation.IndexOf(cellX, cellZ);

        // Off the map: nothing to drive onto, so the rail closes the edge.
        if (neighbour < 0)
        {
            return true;
        }

        return !bridgeworks.HasBlock(neighbour) && !terrain.IsPassable(neighbour, MovementClass.Tracked);
    }

    /// <summary>Draws what <see cref="Collect"/> gathered, one instanced call per model.</summary>
    /// <returns>The draw calls issued.</returns>
    public int Draw()
    {
        int calls = 0;

        if (_blockCount > 0 && _block is not null)
        {
            _renderer.Draw(_block, _blocks, _blockCount);
            calls++;
        }

        if (_railCount > 0 && _rail is not null)
        {
            _renderer.Draw(_rail, _rails, _railCount);
            calls++;
        }

        return calls;
    }

    /// <summary>
    /// The colour a block's rail is painted in: the owning team's faction colour. The kit's paint
    /// mask is what makes it apply to the kerbs alone — the deck's planks carry a mask of zero and
    /// are left in their own timber — so a tint handed to every block paints exactly one part of it.
    /// </summary>
    private static Vector4 OwnerColour(int team)
    {
        if ((uint)team >= SimConstants.TeamCount)
        {
            return Vector4.One;
        }

        Color colour = FactionPalette.Primary(SimWorld.FactionOfTeam(team));
        return colour.ToVector4();
    }

    public void Dispose()
    {
        _block?.Dispose();
        _rail?.Dispose();
        _block = null;
        _rail = null;
        _blocks = [];
        _rails = [];
    }
}
