using MiVic.Core.Numerics;
using MiVic.Core.Pathfinding;
using MiVic.Core.Sim;
using MiVic.Game.Data;
using MiVic.Game.Rendering.Gltf;
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;

namespace MiVic.Game.Rendering;

/// <summary>
/// Draws the deck of every crossing on the map, one block per cell, from models generated by
/// <c>tools/blender/build_bridge.py</c>.
/// <para>
/// <b>A crossing is one block repeated.</b> The whole of a bridge — one cell or twenty-four —
/// is the same mesh placed once per cell of the span, turned to the way the span runs. That is
/// what makes the art affordable and the damage legible: a hole is a block that is not drawn,
/// so the player sees exactly which section the artillery took out, and a fifteen-cell crossing
/// costs one more instance rather than one more model.
/// </para>
/// <para>
/// The block is laid on the <em>water line</em>, not on the ground: the piers in the model stop
/// at its own base and what they continue into is the lake, which is opaque and drawn first. A
/// crossing is therefore placed by the surface the player sees rather than by the bed metres
/// under it, which is the same rule the click projection follows.
/// </para>
/// <para>
/// The kerbs are painted in the owner's colour, which is what the kit's paint mask is for: the
/// per-instance tint is the faction's colour, the deck's planks carry a mask of zero and keep
/// their timber, and the rail along each side says whose crossing this is without a flag.
/// </para>
/// </summary>
public sealed class BridgeRenderer : IDisposable
{
    /// <summary>The generated block models: the span, and the crossroads block.</summary>
    private static readonly string BlockFile = "bridge_block.glb";
    private static readonly string JunctionFile = "bridge_junction.glb";

    private static readonly string ModelFolder = Path.Combine("Content", "Models", "Generated");

    private readonly InstancedRenderer _renderer;
    private readonly List<string> _missing = [];

    private InstancedRenderer.Mesh? _block;
    private InstancedRenderer.Mesh? _junction;

    // Two arrays rather than one, because an instanced draw call takes a contiguous run: the
    // straight blocks and the junction blocks are different meshes and cannot share an array.
    private InstanceData[] _straight = [];
    private InstanceData[] _crossroads = [];
    private int _straightCount;
    private int _crossroadsCount;

    public BridgeRenderer(InstancedRenderer renderer, string baseDirectory)
    {
        ArgumentNullException.ThrowIfNull(renderer);
        ArgumentException.ThrowIfNullOrWhiteSpace(baseDirectory);

        _renderer = renderer;

        // No rescaling and no orientation fixup: the block is modelled in metres at the size of
        // one navigation cell, long along its own X, and the placement below turns it.
        ModelImportOptions options = new(
            TargetSizeMetres: 0f,
            AlignLongestHorizontalAxis: false);

        _block = Load(baseDirectory, BlockFile, options);
        _junction = Load(baseDirectory, JunctionFile, options);
    }

    /// <summary>How many block models loaded: two when the art is complete, none when it is absent.</summary>
    public int ShapeCount => (_block is null ? 0 : 1) + (_junction is null ? 0 : 1);

    /// <summary>What was loaded and what was not, for the fixtures and the report.</summary>
    public string Summary => _block is not null && _junction is not null
        ? $"{BlockFile} and {JunctionFile} loaded"
        : _missing.Count == 0
            ? "no bridge blocks loaded"
            : $"bridge blocks missing: {string.Join(", ", _missing)}";

    private InstancedRenderer.Mesh? Load(string baseDirectory, string file, ModelImportOptions options)
    {
        string path = Path.Combine(baseDirectory, ModelFolder, file);

        if (!File.Exists(path))
        {
            _missing.Add(file);
            return null;
        }

        try
        {
            ModelData model = GltfLoader.LoadModel(path, options);
            return _renderer.CreateMesh(ModelBake.Flatten(model, out _));
        }
        catch (Exception exception) when (exception is IOException or InvalidDataException or NotSupportedException)
        {
            _missing.Add($"{file}: {exception.Message}");
            return null;
        }
    }

    /// <summary>
    /// Collects one instance per deck block on the map. Returns how many instances were written.
    /// <para>
    /// Walked by cell rather than by crossing, because a block belongs to the cell: that is what
    /// makes a destroyed block a hole in the deck and a crossing of two spans one junction block
    /// rather than two decks drawn through each other.
    /// </para>
    /// </summary>
    public int Collect(SimWorld world)
    {
        ArgumentNullException.ThrowIfNull(world);

        _straightCount = 0;
        _crossroadsCount = 0;

        if (_block is null)
        {
            return 0;
        }

        Bridgeworks bridgeworks = world.Bridgeworks;
        NavGrid navigation = world.Navigation;
        float water = world.TerrainTypes.WaterLevelMm / (float)WorldPos.MmPerMetre;

        if (_straight.Length < bridgeworks.CellCount)
        {
            _straight = new InstanceData[bridgeworks.CellCount];
            _crossroads = new InstanceData[bridgeworks.CellCount];
        }

        for (int index = 0; index < bridgeworks.CellCount; index++)
        {
            if (!bridgeworks.TryGetBlock(index, out BridgeBlock block))
            {
                continue;
            }

            // The model is long along its own X, which is the axis a span along X runs; a span
            // along Z is the same block turned a quarter turn.
            Matrix turn = block.Axis == BridgeAxis.AlongZ
                ? Matrix.CreateRotationY(MathHelper.PiOver2)
                : Matrix.Identity;

            float x = (navigation.OriginMm + (navigation.CellX(index) * navigation.CellSizeMm) + (navigation.CellSizeMm / 2))
                / (float)WorldPos.MmPerMetre;
            float z = (navigation.OriginMm + (navigation.CellZ(index) * navigation.CellSizeMm) + (navigation.CellSizeMm / 2))
                / (float)WorldPos.MmPerMetre;

            var instance = new InstanceData(
                turn * Matrix.CreateTranslation(x, water, z),
                OwnerColour(block.Team));

            if (block.Axis == BridgeAxis.Junction && _junction is not null)
            {
                _crossroads[_crossroadsCount++] = instance;
            }
            else
            {
                _straight[_straightCount++] = instance;
            }
        }

        return _straightCount + _crossroadsCount;
    }

    /// <summary>Draws what <see cref="Collect"/> gathered, one instanced call per block model.</summary>
    /// <returns>The draw calls issued.</returns>
    public int Draw()
    {
        int calls = 0;

        if (_straightCount > 0 && _block is not null)
        {
            _renderer.Draw(_block, _straight, _straightCount);
            calls++;
        }

        if (_crossroadsCount > 0 && _junction is not null)
        {
            _renderer.Draw(_junction, _crossroads, _crossroadsCount);
            calls++;
        }

        return calls;
    }

    /// <summary>
    /// The colour a block's rail is painted in: the owning team's faction colour. The kit's paint
    /// mask is what makes it apply to the kerbs alone — the deck's planks carry a mask of zero and
    /// are left in their own timber — so a tint handed to every block paints exactly one part of it.
    /// </summary>
    private static Vector4 OwnerColour(int team)
    {
        if ((uint)team >= SimConstants.TeamCount)
        {
            return Vector4.One;
        }

        Color colour = FactionPalette.Primary(SimWorld.FactionOfTeam(team));
        return colour.ToVector4();
    }

    public void Dispose()
    {
        _block?.Dispose();
        _junction?.Dispose();
        _block = null;
        _junction = null;
        _straight = [];
        _crossroads = [];
    }
}
