using MiVic.Core.Numerics;
using MiVic.Core.Sim;
using MiVic.Core.Terrain;

namespace MiVic.Core.Tests.Sim;

/// <summary>
/// Where produced structures and units are allowed to appear.
/// <para>
/// They are placed at a fixed offset from whatever made them, and that offset knows
/// nothing about the map — so a factory on a shoreline would eventually put its next
/// building in the lake, on whichever tick the offset happened to point that way. A
/// building in the sea is not merely odd: it is a structure the player cannot reach.
/// </para>
/// </summary>
public sealed class SpawnPlacementTests
{
    [Fact]
    public void ASiteInWaterIsMovedOntoSolidGround()
    {
        SimWorld world = Build();

        int water = FindSurface(world, TerrainType.DeepWater, TerrainType.ShallowWater);

        Assert.True(
            water >= 0,
            $"the test map has no water in it, so it proves nothing. Surfaces: {Histogram(world)}");

        WorldPos wanted = CentreOf(world, water);
        WorldPos placed = world.LegalSpawnSite(wanted);

        Assert.True(
            IsSolidGround(world, placed),
            $"a spawn site in water was left at {placed.X},{placed.Z}");

        // Moved, but not flung: the site is searched for ring by ring around where it
        // was wanted, so the result is within the search radius in cells. A cell in the
        // middle of a lake legitimately moves a long way, which is why this counts
        // cells rather than metres.
        int wantedCell = world.Navigation.IndexOfWorld(wanted);
        int placedCell = world.Navigation.IndexOfWorld(placed);

        int dx = Math.Abs(world.Navigation.CellX(placedCell) - world.Navigation.CellX(wantedCell));
        int dz = Math.Abs(world.Navigation.CellZ(placedCell) - world.Navigation.CellZ(wantedCell));

        Assert.True(
            Math.Max(dx, dz) <= SimWorld.MaxSpawnSearchCells,
            $"the site moved {Math.Max(dx, dz)} cells, further than the search radius");
    }

    [Fact]
    public void ASiteInLavaIsMovedOntoSolidGround()
    {
        SimWorld world = Build();

        int lava = FindSurface(world, TerrainType.Lava);

        if (lava < 0)
        {
            // Lava is generated by volcanoes, which this seed may not have placed.
            return;
        }

        WorldPos placed = world.LegalSpawnSite(CentreOf(world, lava));

        Assert.True(IsSolidGround(world, placed), "a spawn site in lava was not moved");
    }

    [Fact]
    public void ASiteOnSolidGroundIsLeftWhereItIs()
    {
        SimWorld world = Build();

        int ground = FindSurface(world, TerrainType.Grass, TerrainType.Rock, TerrainType.Sand);

        Assert.True(ground >= 0);

        WorldPos wanted = CentreOf(world, ground);

        Assert.Equal(wanted, world.LegalSpawnSite(wanted));
    }

    /// <summary>
    /// The standard map has volcanoes on it.
    /// <para>
    /// This is not a truism. The volcano line was once the top twelfth of the map's
    /// highest <em>value</em> rather than of its relief, which on this map sat above
    /// every square of ground: a volcano feature, a lava hazard and a lava surface
    /// shader, with no lava anywhere to reach any of them. A test that counts is the
    /// only kind that notices a feature which exists and never happens.
    /// </para>
    /// </summary>
    [Fact]
    public void TheStandardMapHasVolcanoes()
    {
        SimWorld world = Build();
        int lava = CountSurface(world, TerrainType.Lava);

        Assert.True(lava > 0, "no lava on the map at all, so the volcano line is above the ground");
    }

    private static int CountSurface(SimWorld world, TerrainType wanted)
    {
        TerrainLayer terrain = world.TerrainTypes;
        int count = 0;

        for (int cell = 0; cell < terrain.Size * terrain.Size; cell++)
        {
            if (terrain.TypeAt(cell) == wanted)
            {
                count++;
            }
        }

        return count;
    }

    /// <summary>How many cells of each surface a world has. For test failure messages.</summary>
    private static string Histogram(SimWorld world)
    {
        var counts = new Dictionary<TerrainType, int>();
        TerrainLayer terrain = world.TerrainTypes;

        for (int cell = 0; cell < terrain.Size * terrain.Size; cell++)
        {
            TerrainType type = terrain.TypeAt(cell);
            counts[type] = counts.GetValueOrDefault(type) + 1;
        }

        return string.Join(", ", counts.OrderByDescending(pair => pair.Value).Select(pair => $"{pair.Key}={pair.Value}"));
    }

    /// <summary>
    /// A real skirmish world. Building the scenario is what generates the terrain —
    /// water, lava and all — so a bare SimWorld has nothing in it to test against.
    /// </summary>
    private static SimWorld Build()
    {
        var world = new SimWorld(seed: 20250101, capacity: 1024);
        Scenario.Build(world, ScenarioKind.Skirmish);

        return world;
    }

    /// <summary>The world position at the centre of a terrain cell.</summary>
    private static WorldPos CentreOf(SimWorld world, int terrainCell)
    {
        TerrainLayer terrain = world.TerrainTypes;
        int x = terrainCell % terrain.Size;
        int z = terrainCell / terrain.Size;

        return new WorldPos(
            terrain.OriginMm + (x * terrain.CellSizeMm) + (terrain.CellSizeMm / 2),
            0,
            terrain.OriginMm + (z * terrain.CellSizeMm) + (terrain.CellSizeMm / 2));
    }

    /// <summary>True when the ground under a position is neither water nor lava.</summary>
    private static bool IsSolidGround(SimWorld world, WorldPos position)
    {
        int cell = world.TerrainTypes.IndexOfWorld(position.X, position.Z);

        if (cell < 0)
        {
            return false;
        }

        TerrainType type = world.TerrainTypes.TypeAt(cell);

        return type is not (TerrainType.ShallowWater or TerrainType.DeepWater or TerrainType.Lava);
    }

    private static int FindSurface(SimWorld world, params TerrainType[] wanted)
    {
        TerrainLayer terrain = world.TerrainTypes;

        for (int cell = 0; cell < terrain.Size * terrain.Size; cell++)
        {
            TerrainType type = terrain.TypeAt(cell);

            foreach (TerrainType candidate in wanted)
            {
                if (type == candidate)
                {
                    return cell;
                }
            }
        }

        return -1;
    }
}
